version: "3.7"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      - network-local
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data/portainer:/data"

networks:
  network-local:
    external: true