pipeline {
    agent any
    environment {
        URL_PUBLISH = 'https://mysite.com'
        IMAGE_DOCKER = 'NAME_IMAGE'
        CHANNEL_SLACK = 'NAME_CHANNEL_SLACK'
    }
    stages {
        stage('Send Notif Start'){
            steps {
                slackSend channel: "${CHANNEL_SLACK}", message: "${URL_PUBLISH} deploy START"
            }
        }
        stage('Docker Down'){
            steps {
                sh "TAG_VERSION=${BUILD_NUMBER - 1} docker compose down"
                sh "docker image remove ${IMAGE_DOCKER}:${BUILD_NUMBER - 1} --force"
            }
        }
        stage('Build Docker'){
            steps {
                sh "TAG_VERSION=${BUILD_NUMBER} docker compose up -d"
                sh 'docker image prune -a -f'
            }
        }
    }

    post {
        always {
            echo 'always'
        }

        success {
            echo 'success'
            slackSend channel: "${CHANNEL_SLACK}", color: 'good', message: "${URL_PUBLISH} deploy SUCCESS"
        }

        unstable {
            echo 'unstable'
        }

        failure {
            echo 'failure'
            slackSend channel: "${CHANNEL_SLACK}", color: 'danger', message: "${URL_PUBLISH} deploy FAILED"
        }
    }
}